language: generic
sudo: required
services:
 - docker

before_install:
  - docker build -t bonsi/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true bonsi/react-test npm test

after_success:
  - docker build -t bonsi/multi-client ./client
  - docker build -t bonsi/multi-nginx ./nginx
  - docker build -t bonsi/multi-server ./server
  - docker build -t bonsi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bonsi/multi-client
  - docker push bonsi/multi-nginx
  - docker push bonsi/multi-server
  - docker push bonsi/multi-worker

