language: generic
sudo: required
services:
 - docker

before_install:
  - docker build -t bonsi/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true bonsi/react-test npm test

after_success:
  - docker build -t bonsi/multi-client ./client
  - docker build -t bonsi/multi-nginx ./nginx
  - docker build -t bonsi/multi-server ./server
  - docker build -t bonsi/multi-worker ./worker
